import nextCoreWebVitals from 'eslint-config-next/core-web-vitals';

/**
 * `next lint` was removed in Next 16, so ESLint runs through its own CLI via
 * `npm run lint`. `eslint-config-next/core-web-vitals` already bundles the base
 * Next rules (react, react-hooks, import, jsx-a11y, @next/next) plus the Core
 * Web Vitals set, which is what `next lint` used to apply.
 */
const config = [
  {
    ignores: [
      '.next/**',
      // Regenerated by fumadocs-mdx at the start of every build.
      '.source/**',
      // Generated by Next; ships with its own triple-slash directives.
      'next-env.d.ts',
    ],
  },
  ...nextCoreWebVitals,
];

export default config;
